---
title: "Credit card fraud analysis"
output:
  pdf_document: default
  html_document: default
date: "2023-12-03"
Author: "Ashutosh, Pratiksha, Huichuan"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(gtsummary)
```

```{r}
ccf<- read.csv("ccf_simulation.csv")
```

```{r}

  ccf<- ccf %>%
            mutate(
              isFraud=factor(isFraud),
                  type= factor(type)
              )
```

```{r}
#Missing values:
ccf<- ccf %>%  filter(amount <8000000)
sum(is.na(ccf))
```

```{r}
   ccf_red<- ccf %>%
           filter(type == c("CASH_OUT","TRANSFER"))
  write.csv(ccf_red, "ccf_red.csv")
```


```{r}

ccf <- ccf %>%
  filter(isFraud == 1) %>%
  slice_sample(n = 1000, replace = FALSE) %>%
    bind_rows(ccf %>%
      filter(isFraud == 0) %>%
        slice_sample(n = 4000, replace = FALSE))

  ccf %>% 
      select(isFraud,type) %>% 
        tbl_summary(
          by=isFraud,
          digits= list(
            all_continuous()~ c(2,2)
            ),
            statistic= list(
              all_continuous()~"{mean} ({sd})"
            )
) 

```

```{r}
ggplot(ccf,aes(fill=type, x= isFraud, group=type))+
  geom_bar(width=1,show.legend = TRUE,col = "red", position= "dodge", aes(y = (..count..)/sum(..count..) * 100)) +
  labs(title = "Distribution of Transaction Types by Fraud Status",
       x = "Transaction Type",
       y = "Percentage") +
  scale_y_continuous(
    labels = scales::percent_format(scale = 1)
    )+scale_x_discrete(labels =c("Not Fraud","Fraud"))

```